"""Researched sources and parameters, 2026-09-18.

`confidence` is honest about provenance:
  verified   - primary text fetched and the number read directly from it
  partial    - from a search-result synthesis of the publisher's own pages,
               primary fetch blocked (403 / DNS)
  unverified - known to exist but not retrieved in this pass; a named gap
"""
D = "2026-09-18"

SOURCES = [
    ("aiken-2014-lancet",
     "Nurse staffing and education and hospital mortality in nine European countries: a retrospective observational study",
     "The Lancet", 2014, "EU", "study",
     "https://doi.org/10.1016/S0140-6736(13)62631-8", D, "web",
     "Aiken LH, Sloane DM, Bruyneel L, et al. Lancet 383(9931):1824-1830. Numbers read from the UNIC research-portal abstract mirror; thelancet.com returned 403."),
    ("snct-nihr-2020",
     "The Safer Nursing Care Tool as a guide to nurse staffing requirements on hospital wards: observational and modelling study",
     "NIHR Journals Library (HS&DR 8.16)", 2020, "UK", "study",
     "https://www.ncbi.nlm.nih.gov/books/NBK555316/", D, "web",
     "Key design input: establishments set to MEAN demand under-deliver; meeting demand 90% of the time gave the best outcomes."),
    ("nice-sg1-2014",
     "Safe staffing for nursing in adult inpatient wards in acute hospitals (SG1)",
     "NICE", 2014, "UK", "guideline",
     "https://www.nice.org.uk/guidance/sg1", D, "web",
     "Primary chapters returned 403; content from NICE's own indexed pages. Establishes that NO single ratio fits all wards - each ward sets its own establishment. This is the mandate for an optimiser rather than a fixed-ratio calculator."),
    ("ewtd-2003-88-ec",
     "Directive 2003/88/EC concerning certain aspects of the organisation of working time",
     "European Parliament and Council", 2003, "EU", "statute",
     "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=celex:32003L0088", D, "web",
     "Healthcare derogations exist (opt-out, reference periods); treat limits as defaults to be overridden per jurisdiction, not absolutes."),
    ("cms-cmi",
     "Case Mix Index: average MS-DRG relative weight across a hospital's inpatient discharges",
     "CMS / industry reference", 2026, "US", "reference",
     "https://www.definitivehc.com/resources/glossary/case-mix-index", D, "web",
     "Definition consistent across sources. CMI 1.0 = Medicare baseline complexity. NOTE: CMI is a REIMBURSEMENT weight, not a nursing-workload weight - see gap.cmi_to_nursing_workload."),
    ("ca-title22-70217",
     "California Code of Regulations Title 22 s.70217, licensed nurse-to-patient ratios (AB 394, 1999)",
     "California DPH", 1999, "US", "statute",
     "https://leginfo.legislature.ca.gov/faces/billTextClient.xhtml?bill_id=199920000AB394", D, "web",
     "GAP: sources disagree between 1:5 and 1:6 for medical/surgical (likely the 2005 phase-down). Primary CDPH and CHCF fetches failed (DNS/timeout). Do not encode until resolved."),
    ("yang-2023-bmcnurs",
     "Construction and application of a nursing human resource allocation model based on the case mix index",
     "BMC Nursing 22:466", 2023, "CN", "study",
     "https://doi.org/10.1186/s12912-023-01632-y", D, "web",
     "Yang Y, He M, Yang Y, et al. THE CMI-to-nursing bridge. 271 inpatients, 36 nurses, one hepatobiliary surgery department, Mianyang Central Hospital, Aug-Sep 2022. Single-department single-country study - the functional FORM is reusable, the COEFFICIENTS are not."),
    ("snct-multipliers-nihr", "SNCT acuity multipliers and HPPD by dependency level (Table 31)",
     "NIHR Journals Library (HS&DR 8.16), Methodological details", 2020, "UK", "standard",
     "https://www.ncbi.nlm.nih.gov/books/NBK555317/", D, "web",
     "The acuity ladder. Level 0 -> Level 3 spans 4.35 -> 26.2 HPPD, a 6.0x spread. Cross-validates with the separately retrieved specialling figure (5.47 multiplier = 24 HPPD): both imply the same WTE-to-HPPD conversion of ~0.228."),
    ("nas-icu-workload", "Nursing Activities Score: 23-item instrument scoring percentage of one nurse's 24h per patient",
     "NAS literature incl. systematic review of 70 studies / 56,000+ ICU patients", 2025, "INTL", "standard",
     "https://www.scielo.br/j/reeusp/a/pWCHRkfXMtswmznjG76qf5v/", D, "web",
     "Independent corroboration from critical care: nursing time per patient ranges 0-176.8% of one nurse-day."),
    ("dallora-2015-bmjopen", "Association of 12 h shifts and nurses job satisfaction, burnout and intention to leave: cross-sectional study of 12 European countries",
     "BMJ Open 5(9):e008331", 2015, "EU", "study",
     "https://doi.org/10.1136/bmjopen-2015-008331", D, "web",
     "Dall'Ora C, Griffiths P, Ball J, Simon M, Aiken LH. RN4CAST, 31,627 registered nurses. Shift length and overtime had independent effects."),
    ("rogers-2004-healthaff", "The working hours of hospital staff nurses and patient safety",
     "Health Affairs 23(4):202", 2004, "US", "study",
     "https://doi.org/10.1377/hlthaff.23.4.202", D, "web",
     "Rogers AE, Hwang WT, Scott LD, Aiken LH, Dinges DF. 393 nurses, 5,317 logged shifts, 199 errors. Authors recommend curtailing routine 12h shifts and eliminating the overtime attached to them. Numbers from secondary summaries; primary full text not retrieved."),
    ("dallora-2025-jamanetwopen", "Nurse staffing configurations and nurse absence due to sickness",
     "JAMA Network Open 8(4):e255946", 2025, "UK", "study",
     "https://doi.org/10.1001/jamanetworkopen.2025.5946", D, "web",
     "18,674 staff, 2,690,080 shifts, 43,097 sickness episodes. ESTABLISHES A FEEDBACK LOOP: understaffing and long shifts raise sickness absence, which worsens staffing."),
    ("kim-2026-jonm", "Data-driven scheduling strategies to minimize fatigue in rotating night-shift nurses",
     "Journal of Nursing Management 2026:9994492", 2026, "INTL", "study",
     "https://doi.org/10.1155/jonm/9994492", D, "web",
     "Quantifies fatigue by shift sequence. Gives directly actionable scheduling limits."),
    ("ball-rn4cast-missed-care", "Care left undone during nursing shifts: associations with workload and perceived quality of care",
     "RN4CAST / Journal of Clinical Nursing", 2020, "UK", "study",
     "https://onlinelibrary.wiley.com/doi/10.1111/jocn.15242", D, "web",
     "86% of UK registered nurses missed at least some necessary care on their last shift; omissions rise as RN staffing falls. The mechanism linking thin staffing to harm. Retrieved at summary level only."),
    ("doh-abudhabi-nursing-scope", "Scope of Practice - Nursing",
     "Department of Health, Abu Dhabi", 2022, "AE", "standard",
     "https://www.doh.gov.ae/-/media/59C71DCFBE58464E9DBCE9463F05DA88.ashx", D, "web",
     "Ties permitted activity to education, licensure and competence. Located, not yet extracted into a role catalogue."),
    ("cno-scope-of-practice", "Scope of Practice Practice Standard",
     "College of Nurses of Ontario", 2023, "CA", "standard",
     "https://cno.org/Assets/CNO/Documents/Standard-and-Learning/Practice-Standards/49041-scope-of-practice.pdf", D, "web",
     "Canadian scope is provincial, not national: CNO (Ontario), BCCNM (BC), CLPNA (Alberta) each define it. RPN is a regulated profession only in BC, AB, SK and MB."),
    ("clpna-lpn-scope", "Determining Licensed Practical Nurse Scope of Practice",
     "College of Licensed Practical Nurses of Alberta", 2024, "CA", "standard",
     "https://www.clpna.com/wp-content/uploads/2024/01/Determining-Licensed-Practical-Nurse-Scope-of-Practice-ID-125614.pdf", D, "web",
     "Practice guideline for deciding whether an activity falls inside LPN scope."),
    ("knauf-2006-niw",
     "Nursing Cost by DRG: Nursing Intensity Weights",
     "Policy, Politics & Nursing Practice", 2006, "US", "study",
     "https://doi.org/10.1177/1527154406297910", D, "web",
     "Knauf RA, Ballard K, Mossman PN, Lichtig LK. The principled DRG->nursing bridge: Nursing Intensity Weights allocate nursing cost per DRG. New York State is the only DRG system that identifies nursing separately. Full text not retrieved - abstract-level only."),
]

PARAMS = [
    # --- acuity / demand ----------------------------------------------------
    ("acuity.snct.hppd_range", "5.9-10.2", "hours/patient/day", "adult inpatient wards",
     "demand", "soft", "snct-nihr-2020",
     "varied from 5.9 to 10.2 hours per patient-day", "verified",
     "Observed range across wards. Use as the sanity band for any computed HPPD - a model output outside it is a bug signal."),
    ("acuity.snct.specialling_multiplier", "5.47", "WTE multiplier", "1:1 specialling",
     "demand", "soft", "snct-nihr-2020",
     "equivalent to 24 HPPD for each patient who required specialling", "verified",
     "Anchors the multiplier-to-HPPD conversion: a 5.47 multiplier equals 24 HPPD."),
    ("demand.establishment_policy", "p90", "percentile of demand", "all units",
     "demand", "soft", "snct-nihr-2020",
     "policies meeting demand 90% of the time produced the best outcomes", "verified",
     "DESIGN-CRITICAL: do not plan to mean demand. Makes coverage a chance constraint at the 90th percentile, not a deterministic equality."),
    ("acuity.cmi.baseline", "1.0", "index", "hospital",
     "acuity", "default", "cms-cmi",
     "A CMI of 1.0 means the hospital's average case matches the Medicare baseline", "partial",
     "CMI scales demand relative to 1.0."),

    # --- skill mix / quality ------------------------------------------------
    ("quality.mortality_or_per_extra_patient", "1.068", "odds ratio (95% CI 1.031-1.106)",
     "surgical inpatients", "skillmix", "soft", "aiken-2014-lancet",
     "odds ratio 1.068, 95% CI 1.031-1.106", "verified",
     "Each additional patient per nurse raises 30-day mortality odds ~7%. This is the quantitative care-quality objective - it turns understaffing into a risk number rather than a vague penalty."),
    ("quality.mortality_or_per_10pct_degree_nurses", "0.929", "odds ratio (95% CI 0.886-0.973)",
     "registered nurses", "skillmix", "soft", "aiken-2014-lancet",
     "0.929, 0.886-0.973", "verified",
     "A 10% larger share of bachelor's-educated nurses lowers mortality odds ~7%. Justifies treating SN share as a quality lever, not only a cost lever."),
    ("skillmix.single_ratio_exists", "false", "boolean", "all wards",
     "skillmix", "hard", "nice-sg1-2014",
     "no single nursing staff-to-patient ratio that can be applied across the whole range of wards", "partial",
     "MANDATE: NICE explicitly rejects a universal ratio and requires ward-level establishment setting. This is why ratios must be an OUTPUT of this app, not an input."),

    # --- wellbeing ----------------------------------------------------------
    ("wellbeing.max_weekly_hours", "48", "hours/week (averaged)", "all staff",
     "wellbeing", "hard", "ewtd-2003-88-ec",
     "average weekly working time shall not exceed 48 hours", "partial",
     "Caps regular plus overtime. NOTE: Model B's 48h week sits exactly at the ceiling, leaving zero legal overtime headroom - the current app lets you add 5h/week anyway."),
    ("wellbeing.min_daily_rest", "11", "consecutive hours per 24h", "all staff",
     "wellbeing", "hard", "ewtd-2003-88-ec",
     "minimum daily rest period of 11 consecutive hours per 24-hour period", "partial",
     "Constrains shift adjacency (no late-then-early)."),
    ("wellbeing.max_night_hours", "8", "hours per 24h (averaged)", "night workers",
     "wellbeing", "hard", "ewtd-2003-88-ec",
     "night work should be no more than 8 hours on average in any 24-hour period", "partial",
     "CONFLICT: Model A's night shift is 10h and Model B's is 12h. Both exceed this default. Derogations may apply - must be an explicit, visible override, never silence."),
    ("wellbeing.min_weekly_rest", "24", "uninterrupted hours per 7 days", "all staff",
     "wellbeing", "hard", "ewtd-2003-88-ec",
     "minimum uninterrupted rest period of 24 hours", "partial", None),

    # --- acuity ladder: the primary demand driver ---------------------------
    ("acuity.snct.hppd_by_level",
     "L0=4.35, L1a=6.10, L1b=7.55, L2=8.65, L3=26.2", "hours/patient/day",
     "general wards", "demand", "soft", "snct-multipliers-nihr",
     "Level 0 0.99 / 1a 1.39 / 1b 1.72 / 2 1.97 / 3 5.96 (WTE multipliers)", "verified",
     "THE BASELINE. Different patients do NOT require the same work time: Level 0 to Level 3 is a 6.0x spread. This supersedes any claim that nursing time is largely fixed per patient - that conclusion came from a single-specialty study with a restricted acuity range, where range restriction attenuated the slope."),
    ("acuity.snct.hppd_by_level_aau",
     "L0=5.58, L1a=7.29, L1b=9.13, L2=9.92, L3=26.2", "hours/patient/day",
     "acute admissions units", "demand", "soft", "snct-multipliers-nihr",
     "acute admissions unit multipliers for levels 0, 1a, 1b, 2 and 3", "verified",
     "Admissions units need MORE per level than general wards - unit type is a second driver alongside acuity."),
    ("demand.snct_uplift", "0.22", "fraction", "establishment uplift",
     "demand", "soft", "snct-multipliers-nihr",
     "a 22% uplift that must be removed when determining the hours needed", "verified",
     "RESOLVES the uplift question. 22% covers annual leave, sickness and training. Supersedes the 1.46 rest factor (undecomposed, single study) and the app's 1.087 (annual leave only). The published HPPD figures EXCLUDE this uplift - they are care hours on the day."),
    ("acuity.nas.range", "0 - 176.8", "% of one nurse's 24h per patient",
     "ICU patients", "demand", "soft", "nas-icu-workload",
     "scores express the percentage of a nurse's time dedicated to a patient over a 24 hour period (range: 0%-176.8%)", "verified",
     "Independent corroboration from a different instrument, setting and continent: per-patient nursing time varies by multiples, not by percentage points."),
    ("acuity.nas.point_value", "4.8", "minutes of RN FTE time per NAS point",
     "ICU", "demand", "soft", "nas-icu-workload",
     "one NAS point reflects 4.8 min of registered nurse (RN) full time equivalent (FTE) time", "verified",
     "100 NAS points = 1 RN FTE. Gives a direct acuity-to-hours conversion for critical care if the app is ever extended there."),
    ("acuity.nas.observed_mean", "66.2", "% (pooled); 45.5-101.8 across 19 adult ICUs",
     "ICU", "demand", "soft", "nas-icu-workload",
     "pooled mean NAS of 66.2%", "verified",
     "A 2.2x spread between the lowest and highest national means, within ICU alone."),

    # --- wellbeing: shift length -------------------------------------------
    ("wellbeing.long_shift.emotional_exhaustion", "1.26", "aOR (95% CI 1.09-1.46)",
     "shifts >=12h vs <=8h", "wellbeing", "soft", "dallora-2015-bmjopen",
     "Emotional exhaustion 1.26 (1.09-1.46)", "verified", None),
    ("wellbeing.long_shift.depersonalisation", "1.21", "aOR (95% CI 1.01-1.47)",
     "shifts >=12h vs <=8h", "wellbeing", "soft", "dallora-2015-bmjopen",
     "Depersonalization 1.21 (1.01-1.47)", "verified", None),
    ("wellbeing.long_shift.low_accomplishment", "1.39", "aOR (95% CI 1.20-1.62)",
     "shifts >=12h vs <=8h", "wellbeing", "soft", "dallora-2015-bmjopen",
     "Low personal accomplishment 1.39 (1.20-1.62)", "verified", None),
    ("wellbeing.long_shift.job_dissatisfaction", "1.40", "aOR (95% CI 1.20-1.62)",
     "shifts >=12h vs <=8h", "wellbeing", "soft", "dallora-2015-bmjopen",
     "Job dissatisfaction 1.40 (1.20-1.62)", "verified", None),
    ("wellbeing.long_shift.intention_to_leave", "1.29", "aOR (95% CI 1.12-1.48)",
     "shifts >=12h vs <=8h", "wellbeing", "soft", "dallora-2015-bmjopen",
     "Intention to leave job 1.29 (1.12-1.48)", "verified",
     "Turnover is a cost as well as a wellbeing outcome - it feeds recruitment and agency spend."),
    ("wellbeing.long_shift.sickness_absence", "1.26", "OR (95% CI 1.19-1.33)",
     "working only long shifts vs none", "wellbeing", "soft", "dallora-2025-jamanetwopen",
     "Working only long shifts vs. no long shifts: OR 1.26 (95% CI, 1.19-1.33)", "verified", None),
    ("quality.long_shift.error_risk", "3.0", "relative risk",
     "shifts >=12.5h", "skillmix", "soft", "rogers-2004-healthaff",
     "three times more likely to make an error", "partial",
     "DIRECTLY INDICTS MODEL B, which is built on 12h shifts. Also the strongest single argument against using overtime to close a demand gap."),

    # --- wellbeing: night work and recovery ---------------------------------
    ("wellbeing.night.sleep_hours", "5.0", "hours (SD 2.2)", "night shift",
     "wellbeing", "soft", "kim-2026-jonm",
     "Sleep duration: 5.0 hours (shortest among all shifts)", "verified", None),
    ("wellbeing.night.fatigued_work_fraction", "0.514", "fraction of shift",
     "single night shift", "wellbeing", "soft", "kim-2026-jonm",
     "Fatigue during work hours: 51.42% of shift time", "verified",
     "Against 0.52% on day shifts and 0.98% on evenings - a ~50x difference. Night work is the dominant wellbeing cost in any 24/7 pattern."),
    ("wellbeing.three_consecutive_nights.fatigued_fraction", "0.347", "fraction of work time",
     "3 consecutive nights", "wellbeing", "soft", "kim-2026-jonm",
     "Fatigue proportion: 34.74% of total work time", "verified",
     "Authors recommend avoiding three or more consecutive night shifts."),
    ("wellbeing.day_shift.fatigued_fraction", "0.0052", "fraction of work time",
     "3 consecutive days", "wellbeing", "soft", "kim-2026-jonm",
     "Three consecutive day shifts (DDD): 0.52% fatigue proportion", "verified",
     "The reference schedule the index is scored against."),
    ("wellbeing.quick_return.threshold", "11", "hours between shifts",
     "shift adjacency", "wellbeing", "hard", "kim-2026-jonm",
     "quick return patterns (< 11 h between shifts) significantly increased fatigue", "verified",
     "Coincides exactly with the EWTD 11h daily rest minimum - an independent line of evidence arriving at the same number."),

    # --- wellbeing: skill mix and the feedback loop -------------------------
    ("wellbeing.rn_share.sickness_absence", "0.98", "OR per +10% RN hours (0.96-0.99)",
     "skill mix", "wellbeing", "soft", "dallora-2025-jamanetwopen",
     "Each 10% increase in proportion of RN hours: OR 0.98 (95% CI, 0.96-0.99)", "verified",
     "A richer RN mix costs more per hour but reduces sickness absence - cost and wellbeing are not purely opposed."),
    ("wellbeing.absence_is_endogenous", "true", "boolean", "model structure",
     "wellbeing", "hard", "dallora-2025-jamanetwopen",
     "Working long shifts and working on understaffed wards increases the risk of sickness absence", "verified",
     "STRUCTURAL. The app treats unplanned absence as a fixed exogenous input. It is not: understaffing raises sickness, which worsens understaffing. Under-provisioning is self-reinforcing, so a plan that looks marginally adequate on paper degrades in service."),
    ("quality.missed_care.prevalence", "0.86", "fraction of RNs",
     "last shift", "skillmix", "soft", "ball-rn4cast-missed-care",
     "86% of registered nurses surveyed in the UK reported that they had missed at least some care", "partial",
     "The mechanism between thin staffing and harm: care is omitted before it is refused."),

    # --- scope of practice --------------------------------------------------
    ("scope.is_jurisdictional", "true", "boolean", "role catalogues",
     "skillmix", "hard", "cno-scope-of-practice", None, "verified",
     "STRUCTURAL. Scope of practice is not universal and often not even national - it is set per province in Canada and per state in the US. A planner that assumes one country's grades will mis-plan in another, so role catalogues are keyed by jurisdiction and non-UK ones are empty stubs rather than UK copies."),
    ("scope.ca_rpn_is_regional", "BC, AB, SK, MB", "provinces", "registered psychiatric nurse",
     "skillmix", "hard", "cno-scope-of-practice",
     "a regulated profession in British Columbia, Alberta, Saskatchewan, and Manitoba", "verified",
     "A grade that exists in four provinces and not the rest - the clearest example of why a single national catalogue is wrong."),
    ("scope.ae_competence_based", "education, licensure, competence", "basis",
     "UAE nursing", "skillmix", "hard", "doh-abudhabi-nursing-scope",
     "supported by their level of education, licensure and competence", "partial",
     "Activity-based rather than grade-based, so mapping onto fixed role categories needs care."),
    ("gap.sa_scope_undefined", "UNRESOLVED", "-", "Saudi nursing categories",
     "skillmix", "hard", "cno-scope-of-practice", None, "unverified",
     "Scope of practice is reportedly not clearly articulated for all nursing categories in Saudi Arabia. For the future regulatory-scraping work this means an empty result may be the CORRECT answer rather than a scraping failure - it needs primary work, not a lookup."),
    ("gap.role_catalogues_unverified", "UK only, unverified", "-", "app/roles.py",
     "skillmix", "hard", "cno-scope-of-practice", None, "unverified",
     "Only the UK catalogue is populated, from a considered reading rather than a citation-backed extract from NMC standards. ES, US, CA, AE and SA are declared stubs. No catalogue is marked verified. See app/roles.py from_regulator() for the intended procedure."),
    ("gap.task_profile_unsourced", "assumption", "fraction per task category",
     "DEFAULT_TASK_PROFILE", "demand", "soft", "snct-nihr-2020", None, "unverified",
     "How care hours divide across task categories is an assumption, not an activity study. It drives how much of the establishment must be registered, so it matters. Replace with local observation, and vary it by unit type - a surgical ward and a stroke unit do not divide their hours alike."),

    # --- named gaps ---------------------------------------------------------
    ("gap.cmi_to_nursing_workload", "RESOLVED-AS-FORM", "-", "core modelling assumption",
     "acuity", "hard", "yang-2023-bmcnurs", None, "partial",
     "RESOLVED 2026-09-18. A validated CMI-to-nursing-worktime mapping exists (yang-2023-bmcnurs), so CMI stays the portable acuity index as intended. But its coefficients are single-department and fail cross-check against SNCT by ~2x. Architecture: CMI drives demand through the quadratic FORM with LOCALLY CALIBRATED coefficients; SNCT's 5.9-10.2 band is the validation gate on the output, not the driver. Remaining gap is calibration data, not method."),
    ("gap.ca_medsurg_ratio", "1:5 or 1:6", "nurse:patients", "medical/surgical",
     "skillmix", "hard", "ca-title22-70217", None, "unverified",
     "Sources conflict; primary fetches failed. Only relevant if US jurisdiction is in scope."),
    ("gap.snct_level_multipliers", "RESOLVED", "multiplier per level", "levels 0,1a,1b,2,3",
     "demand", "soft", "snct-multipliers-nihr", None, "verified",
     "RESOLVED 2026-09-18 from NIHR Table 31 - see acuity.snct.hppd_by_level. The Shelford pack itself remains proprietary, but the NIHR study reproduces the published multipliers."),
    ("acuity.cmi_to_dnw.form", "DNW = 92.3 + 4.8*CMI + 2.4*CMI^2", "minutes/patient/day",
     "demand model functional form", "acuity", "default", "yang-2023-bmcnurs",
     "DNW = 92.3 + 4.8*CMI + 2.4*CMI2 (R2 = 0.627, F = 225.1, p < 0.001)", "verified",
     "THE BRIDGE. Note it is QUADRATIC and convex, not linear - a plain HPPD x CMI scaling is wrong even where the relationship holds. CMI is a parameter, not a decision variable, so demand is computed before the solve and the MILP stays linear."),
    ("acuity.cmi_to_dnw.r_squared", "0.627", "R^2", "CMI as workload predictor",
     "acuity", "soft", "yang-2023-bmcnurs",
     "R2 = 0.627", "verified",
     "CMI explains ~63% of nursing-worktime variance. The unexplained 37% is precisely why coverage must be a p90 chance constraint rather than planning to the point estimate. Locks together with demand.establishment_policy."),
    ("acuity.cmi_to_dnw.coefficients_transfer", "false", "boolean", "cross-hospital use",
     "acuity", "hard", "yang-2023-bmcnurs", None, "verified",
     "CROSS-CHECK FAILED, deliberately recorded. The published coefficients yield 1.66 HPPD at CMI 1.0, or 2.91 HPPD after the study's own mobility (1.2) and rest (1.46) factors - against the SNCT observed band of 5.9-10.2 HPPD. Roughly 2x apart. The form transfers; the coefficients must be locally calibrated. Two independent sources disagreeing by 2x is a finding, not a failure."),
    ("demand.mobility_factor", "1.2", "multiplier", "bed utilisation headroom",
     "demand", "default", "yang-2023-bmcnurs",
     "mobility factor of 1.2", "verified", None),
    ("demand.rest_factor", "1.46", "multiplier", "absence/leave uplift",
     "demand", "default", "yang-2023-bmcnurs",
     "rest factor of 1.46", "verified",
     "BENCHMARK MISMATCH: the current app's implicit uplift is only 2080/1914 = 1.087 from vacation_days alone. It has no allowance for sickness, study leave or parental leave. Establishments will be systematically under-provisioned even after the arithmetic fix."),
    ("quality.staffing_gap_vs_satisfaction", "0.653", "Pearson r (p = 0.006)",
     "theoretical vs actual staffing gap", "skillmix", "soft", "yang-2023-bmcnurs",
     "patient satisfaction (r = 0.653, p = 0.006)", "verified", None),
    ("quality.staffing_gap_vs_adverse_events", "-0.567", "Pearson r (p = 0.021)",
     "theoretical vs actual staffing gap", "skillmix", "soft", "yang-2023-bmcnurs",
     "adverse events (r = -0.567, p = 0.021)", "verified",
     "Independent corroboration of the Aiken direction: closing the staffing gap lowers adverse events."),
    ("acuity.niw.exists", "true", "boolean", "DRG-based nursing weighting",
     "acuity", "soft", "knauf-2006-niw", None, "partial",
     "Preferred long-term route if a DRG feed is available: Nursing Intensity Weights weight each DRG by nursing resource directly, rather than borrowing a reimbursement weight. Full text not retrieved - promote to a task if DRG-level data exists."),
]

RETRIEVALS = [
    ("CMS case mix index definition DRG relative weight", "WebSearch", D,
     "definition obtained, consistent across sources"),
    ("NICE safe staffing adult inpatient wards nursing hours per patient day", "WebSearch", D,
     "SG1 found; confirmed no universal ratio"),
    ("California AB 394 nurse to patient ratio medical surgical Title 22", "WebSearch", D,
     "CONFLICT 1:5 vs 1:6 - logged as gap"),
    ("European Working Time Directive 2003/88/EC limits", "WebSearch", D,
     "48h week / 11h rest / 8h night / 24h weekly obtained"),
    ("Safer Nursing Care Tool multipliers per acuity level", "WebSearch", D,
     "per-level multipliers NOT public - logged as gap"),
    ("Aiken 2014 Lancet nurse staffing mortality", "WebSearch", D, "study located"),
    ("nice.org.uk/guidance/sg1/chapter/Recommendations", "WebFetch", D, "FAILED 403"),
    ("nice.org.uk/guidance/sg1/chapter/Safe-nursing-indicators", "WebFetch", D, "FAILED 403"),
    ("ncbi.nlm.nih.gov/books/NBK555329 (SNCT methods)", "WebFetch", D,
     "specialling multiplier 5.47 equals 24 HPPD"),
    ("ncbi.nlm.nih.gov/books/NBK555316 (SNCT summary)", "WebFetch", D,
     "5.9-10.2 HPPD range; p90 establishment policy"),
    ("pubmed.ncbi.nlm.nih.gov/24581683", "WebFetch", D, "FAILED cookie wall"),
    ("thelancet.com PIIS0140-6736(13)62631-8", "WebFetch", D, "FAILED 403"),
    ("pure.unic.ac.cy Aiken abstract mirror", "WebFetch", D,
     "OR 1.068 and 0.929 with CIs obtained"),
    ("ulh.nhs.uk Shelford SNCT pack", "WebFetch", D, "FAILED DNS"),
    ("cdph.ca.gov AFL-08-07", "WebFetch", D, "FAILED DNS"),
    ("chcf.org min nurse staffing ratios PDF", "WebFetch", D, "FAILED timeout"),
    ("nursing intensity weights DRG nursing care hours per case", "WebSearch", D,
     "NIW concept located (knauf-2006-niw); NY State only DRG system pricing nursing separately"),
    ("case mix index correlation nursing workload validity", "WebSearch", D,
     "FOUND THE BRIDGE: quadratic CMI-to-nursing-worktime model, R2 0.627"),
    ("Dall Ora 12 hour shifts burnout intention to leave RN4CAST", "WebSearch", D,
     "study located; n=31,627 across 12 countries"),
    ("Rogers 2004 Health Affairs nurse hours errors", "WebSearch", D,
     "3x error risk at >=12.5h obtained from secondary summaries"),
    ("quick return 11 hours consecutive nights nurse fatigue", "WebSearch", D,
     "Kim 2026 located; quick-return and consecutive-night effects"),
    ("Ball missed nursing care left undone RN4CAST", "WebSearch", D,
     "86% missed-care prevalence; summary level only"),
    ("nurse staffing sickness absence longitudinal", "WebSearch", D,
     "FEEDBACK LOOP FOUND: understaffing -> sickness -> understaffing"),
    ("pmc.ncbi.nlm.nih.gov/articles/PMC4577950 (Dall Ora 2015)", "WebFetch", D,
     "all six adjusted odds ratios with CIs obtained"),
    ("pmc.ncbi.nlm.nih.gov/articles/PMC13385972 (Kim 2026)", "WebFetch", D,
     "fatigue fractions by shift sequence obtained"),
    ("pmc.ncbi.nlm.nih.gov/articles/PMC12015667 (Dall Ora 2025)", "WebFetch", D,
     "sickness-absence ORs for long shifts, skill mix, part-time, bank/agency"),
    ("frontiersin.org safe limits on work hours review", "WebFetch", D, "FAILED DNS timeout"),
    ("nursing regulator scope of practice Spain TCAE Canada LPN RPN UAE Saudi", "WebSearch", D,
     "regulators located for CA and AE; SA scope reportedly not articulated for all categories; ES/TCAE not found"),
    ("SNCT acuity level 0 1a 1b 2 3 multiplier table", "WebSearch", D,
     "confirmed 5 levels + 22% uplift; multipliers proprietary to Shelford"),
    ("RAFAELA OPCq nursing intensity classification", "WebSearch", D,
     "OPCq/PAONCIL located; 25.2 NCI points per nurse on adult wards"),
    ("Nursing Activities Score NAS ICU nursing time", "WebSearch", D,
     "0-176.8% range, 4.8 min/point, pooled mean 66.2% obtained"),
    ("ncbi.nlm.nih.gov/books/NBK555317 (SNCT Table 31)", "WebFetch", D,
     "FULL MULTIPLIER TABLE OBTAINED - general wards and acute admissions units"),
    ("partnersinpaediatrics.org CYP-SNCT PDF", "WebFetch", D, "FAILED - unparseable PDF"),
    ("pmc.ncbi.nlm.nih.gov/articles/PMC10698983 (Yang 2023)", "WebFetch", D,
     "equation, R2, units, sample, staffing formula and outcome correlations all obtained"),
    ("pubmed.ncbi.nlm.nih.gov/17242393 (Knauf NIW)", "WebFetch", D, "FAILED cookie wall"),
    ("ncbi.nlm.nih.gov/pmc/articles/PMC10698983", "WebFetch", D, "301 redirect to pmc.ncbi.nlm.nih.gov"),
]


def seed(conn):
    with conn:
        conn.execute("DELETE FROM parameters")
        conn.execute("DELETE FROM sources")
        conn.execute("DELETE FROM retrievals")
        for s in SOURCES:
            conn.execute(
                "INSERT INTO sources (slug,title,publisher,year,jurisdiction,doc_type,url,"
                "retrieved_at,retrieval,notes) VALUES (?,?,?,?,?,?,?,?,?,?)", s)
        for key, val, unit, applies, kind, binding, src, quote, conf, notes in PARAMS:
            row = conn.execute("SELECT id FROM sources WHERE slug=?", (src,)).fetchone()
            conn.execute(
                "INSERT INTO parameters (key,value,unit,applies_to,kind,binding,source_id,"
                "quote,confidence,notes) VALUES (?,?,?,?,?,?,?,?,?,?)",
                (key, val, unit, applies, kind, binding, row[0] if row else None,
                 quote, conf, notes))
        for r in RETRIEVALS:
            conn.execute("INSERT INTO retrievals (query,tool,ran_at,result_note) "
                         "VALUES (?,?,?,?)", r)
